WIP: WallオプションででるWarningを消す
ut-issl/c2a-core pull request #59
Opened 2021-11-27 17:36 UTC by meltingrabbit

## 概要
WallオプションででるWarningを消す

## Issue
- https://github.com/ut-issl/c2a-core/issues/27

## 詳細
- WallオプションででるWarningを消す
- Warningが出たときはCIを落とすように
- Wextra については別で

## 検証結果
- CIが通る
- 既存のtestがすべて通る

## 影響範囲
今後，WarningがあるPRは通らなくなる

## 補足
NA

2021-11-27 17:39 UTC, meltingrabbit commented
-Werror オプションをつけると， https://github.com/ut-issl/c2a-core/runs/4341988868?check_suite_focus=true のように確かに落ちたが，Warningが出た時点でコンパイルが止まった．

できれば最後までコンパイルし，Warning一覧を見たいところ．

2021-11-27 17:40 UTC, meltingrabbit commented
コンパイル結果をファイルに出力し，grepするのがいいのかしら？

2021-11-28 16:09 UTC, meltingrabbit commented
CIは落とさない WextraのビルドCIをいれた

2021-11-28 17:06 UTC, meltingrabbit commented
Wextraはともかく（多少減らしたけど），Wallは一旦全て消えたのでは？

2021-11-28 17:16 UTC, sksat requested changes

2021-11-28 17:16 UTC, sksat commented on CmdTlm/packet_list.c
> +  return (uint16_t)(pli->total_nodes_ - pli->active_nodes_);
どっちのメンバも`uint16_t`なのでそもそもキャストが要らなさそう

2021-11-28 17:20 UTC, meltingrabbit commented on CmdTlm/packet_list.c
> +  return (uint16_t)(pli->total_nodes_ - pli->active_nodes_);
汎整数拡張って，暗黙的にintにならなかったっけ？（ちょっとコンパイルしてみます）

2021-11-28 17:21 UTC, sksat commented on CmdTlm/packet_list.c
> +  return (uint16_t)(pli->total_nodes_ - pli->active_nodes_);
アーッ汎整数拡張

2021-11-28 17:21 UTC, meltingrabbit commented on CmdTlm/packet_list.c
> +  return (uint16_t)(pli->total_nodes_ - pli->active_nodes_);
キャストないとWarningでちゃうね．(Conversion in return)

2021-11-28 17:22 UTC, meltingrabbit commented on CmdTlm/packet_list.c
> +  return (uint16_t)(pli->total_nodes_ - pli->active_nodes_);
u16 + u16が u16にならないの，結構だるいこと多いいんだよね．．．

2021-11-28 17:26 UTC, sksat commented on CmdTlm/packet_list.c
> +  return (uint16_t)(pli->total_nodes_ - pli->active_nodes_);
C言語筋が衰えていました...そうだった...

2021-11-28 17:28 UTC, sksat commented on Examples/minimum_user_for_s2e/CMakeLists.txt
> +    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Werror")
これは`target_compile_options()`でやるべきですが，どうせ後で直すので一旦スルー

2021-11-28 17:29 UTC, sksat approved these changes

2021-11-28 17:29 UTC, meltingrabbit commented
Cmakeまわりは https://github.com/ut-issl/c2a-core/pull/35 でお願いするとして，マージします．

2021-11-28 17:30 UTC, merged