git_revision.cをどうにかする
ut-issl/c2a-core pull request #82
Opened 2021-12-06 11:49 UTC by sksat

## 概要
`git_revision.c`がトラッキングされていると，ビルドする度に無意味なdiffが発生する上誤ってcommitしてしまうことがある．
そのため，ソースディレクトリ中に`git_revision_template.c`を置き，そこから`git_revision.c`を生成するようにする．

## Issue
- 関連する issue

## 詳細
- [x] `git_revision.tmp`は分かりにくいので`git_revision.c`と同じディレクトリに移す
- [x] `add_custom_command()`を適切な場所に移す
- [ ] `git_revision_template.c`をコンパイル可能にする

## 検証結果
test へのリンクや，検証結果へのリンク

## 影響範囲
`git_revision.sh`などを自動で実行できない環境では`git_revision_template.c`を使ってもらう必要がある

## 補足
何かあれば

## 注意
- 関連する Projects が存在する場合，それの紐付けを行うこと
- Assignees を設定すること
- 可能ならば Reviewers を設定すること
- 可能ならば `priority` ラベルを付けること

2021-12-06 11:50 UTC, sksat commented
あとは`git_revision_template.c`がCとして合法になっていればいい

2021-12-06 11:52 UTC, sksat commented
え，S2E系のCIだけ落ちてる...まさか...

2021-12-06 11:57 UTC, sksat commented
`if(WIN32)`の方書き方ミスってただけだった．よかった．

2021-12-06 12:01 UTC, sksat commented
`git_revision_template.c`を合法にするの，微妙に面倒なのでifdefしたらいい気もする

2021-12-07 11:32 UTC, sksat commented
conflictしてたのでrebase

2021-12-10 11:49 UTC, sksat commented
再rebase

2021-12-10 11:55 UTC, sksat commented
あと微塵もLibraryではないし`src_user`直下でもいい気もするんだよな

2021-12-10 11:57 UTC, sksat commented
というか`.c`じゃなくてヘッダを生成する方がまだだいぶマシだなあ．そうするか．

2021-12-10 11:59 UTC, sksat commented
coreに`git_revision.c`だけを置いておいて，そこから`src/src_user/git_revision.h`をinclude，でよいのでは？だいぶシンプルになる．

2021-12-10 12:01 UTC, sksat commented
というかそれなら`git_revision.c`が要らないな．`c2a_core_main.c`でやってしまえばいい．

2021-12-10 12:12 UTC, sksat commented
いや`src/src_user/git_revision.h`も要らないな

2021-12-13 05:45 UTC, meltingrabbit commented
> 各userでsrc/src_user/Library/git_revision.cではなくsrc/src_core/git_revision.cを使ってもらうように変更する必要がある

core rootに `c2a_core_main.c` 以外置きたくないんだけど，（rootにソースコードがたくさんあるの好きじゃない & 他のtool群（各種チェックスクリプトとか，pragma生成スクリプトとか）がその１つ下の階層にファイルがあることを暗に仮定してしまっている），rootがよい強いモチベーションある？

なければ， `core/Lib` 配下か，`core/Hoge` を新しく作ってそこに入れるか，がよいなぁと．

Hogeとしては，userに合わせるなら `Settings` とかになるかなぁ．

2021-12-13 05:46 UTC, meltingrabbit commented on c2a_core_main.c
>    Printf("C2A_init: CA_initialize done.\n");
[NITS] 入れるなら， `CA_initialize()` より前？

2021-12-13 05:47 UTC, meltingrabbit commented
バッチファイル消えてるけど，CMakeLists を使わない環境だとどうなる？（つまりHEW）

2021-12-13 05:51 UTC, sksat commented on c2a_core_main.c
>    Printf("C2A_init: CA_initialize done.\n");
たしかに．そもそもこのPRの確認用に入れてただけなんで入れる必要は無いですけどね．
でもどうせ色々出力してるなら出しちゃっていいのではと思ったんですがどうでしょう？

2021-12-13 05:53 UTC, meltingrabbit commented on c2a_core_main.c
>    Printf("C2A_init: CA_initialize done.\n");
出していいと思うよ～．で場所も先頭で良さそう．

2021-12-13 05:59 UTC, sksat commented on c2a_core_main.c
>    Printf("C2A_init: CA_initialize done.\n");
こういうのってある程度初期化しないと文字列表示できないがちなので癖で適当なinitializeの下で`Printf`既に使ってるところに入れてたけどなんも関係無かったですね．そういう初期化生えるとしても先頭に入れればいいし．

2021-12-13 06:01 UTC, meltingrabbit commented on c2a_core_main.c
>    Printf("C2A_init: CA_initialize done.\n");
`CA_initialize` ではデバッグ出力の初期化は何もしてないしね．

現MOBC環境は，最序盤で呼ばれるbootlader initで初期化されてる．

2021-12-13 06:02 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Script/git_revision.bat
> -@ECHO OFF
バッチファイル消えてるけど，CMakeLists を使わない環境だとどうなる？（つまりHEW）

2021-12-13 06:03 UTC, meltingrabbit commented on git_revision.c
> +#pragma section REPRO
> 各userでsrc/src_user/Library/git_revision.cではなくsrc/src_core/git_revision.cを使ってもらうように変更する必要がある

core rootに c2a_core_main.c 以外置きたくないんだけど，（rootにソースコードがたくさんあるの好きじゃない & 他のtool群（各種チェックスクリプトとか，pragma生成スクリプトとか）がその１つ下の階層にファイルがあることを暗に仮定してしまっている），rootがよい強いモチベーションある？

なければ， core/Lib 配下か，core/Hoge を新しく作ってそこに入れるか，がよいなぁと．

Hogeとしては，userに合わせるなら Settings とかになるかなぁ．

2021-12-13 06:12 UTC, sksat commented on git_revision.c
> +#pragma section REPRO
rootにソースコードが大量にあるの好きじゃないは分かるんですが，mainがrootに転がってる以上はどこにも属さないやつはrootにあった方がいいです．ソースコードの関心領域がわかりやすいようにディレクトリ切ってるはずなのに，その分類が適切でないと元も子もない．あと，このPRでは`git_revision.c`,`git_revision.h`は自動生成しないし二度と弄らなくなるのでチェックスクリプトとかは気にしなくていいかなあ．

不要なファイル分割が微妙ということであれば(このPRでの)`git_revision.c`は`c2a_core_main.c`にあってもいいのでは，とは思ってます．それで`git_revision.h`をLibraryに押し込むのはアリかなあ．

2021-12-13 06:17 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Script/git_revision.bat
> -@ECHO OFF
プロジェクトファイルの`src/src_user/Library/git_revision.c`を見てるところを`src/src_core/git_revision.c`に変えてもらえばビルドはできるようになります．が，HEWってビルド時にバッチファイル自動で動かせてるんでしたっけ．

2021-12-13 06:19 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Script/git_revision.bat
> -@ECHO OFF
バッチファイルは動かせるよ．

じゃあuser側で適当にバッチファイルを配置し，それを走らせて `git_revision.h` を上書きすればいいか．

あれ？ってなると，

> git_revision.cがトラッキングされていると，ビルドする度に無意味なdiffが発生する上誤ってcommitしてしまうことがある．

は結局解決されないことになる？

2021-12-13 06:21 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Script/git_revision.bat
> -@ECHO OFF
それに今気付いてハッとしてました．そのバッチファイル中でコンパイルオプション追加できれば同じようにいけるけど...

2021-12-13 06:23 UTC, meltingrabbit commented on git_revision.c
> +#pragma section REPRO
.h で extern const してる以上，この `git_revision.h` は他の場所でincludeされちゃうのよね（確実にあるのは， `telemetry_source.h` から）

なので，

> git_revision.cはc2a_core_main.cにあってもいいのでは，とは思ってます．それでgit_revision.hをLibraryに押し込むのはアリかなあ．

で，.cの中身は `c2a_core_main.c` に入れちゃって， `.h` はLibに配置する，がまあいいかも．

2021-12-13 06:24 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Script/git_revision.bat
> -@ECHO OFF
NMakeってしってる？

2021-12-13 06:24 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Script/git_revision.bat
> -@ECHO OFF
そこで消耗するのも嫌だしどうせうまくいかない環境出てきた時にダメだ〜となるのも嫌なので，userに`git_revision_config.h`みたいなやつを作ってそこで分岐するか...？

2021-12-13 06:24 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Script/git_revision.bat
> -@ECHO OFF
NMake！！！！！！！

2021-12-13 06:26 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Script/git_revision.bat
> -@ECHO OFF
まあ，すくなくともNMake対応はやめましょうｗ

2021-12-13 06:28 UTC, meltingrabbit commented on git_revision.h
> +#endif
[NITS] 規約的に，プリプロセッサディレクティブはインデント禁止だった

2021-12-13 06:29 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Script/git_revision.bat
> -@ECHO OFF
PMakeならまだしも(それでもGNU Makeと両方で動くようにするのは地獄)，NMakeだけは勘弁してほしい感ありますね...

2021-12-13 06:30 UTC, sksat commented on git_revision.h
> +#endif
正しそう．そうします．

2021-12-13 06:30 UTC, sksat commented on c2a_core_main.c
>    Printf("C2A_init: CA_initialize done.\n");
あーブートローダでやってるのか．なるほど．

2021-12-13 06:31 UTC, meltingrabbit commented on c2a_core_main.c
>    Printf("C2A_init: CA_initialize done.\n");
すくなくとも，デバッグ出力周りの初期化はcore initではなくuser init or bootloaderですべきなので，ここではデバッグ出力使える前提でOKですね

2021-12-13 06:32 UTC, sksat commented on c2a_core_main.c
>    Printf("C2A_init: CA_initialize done.\n");
ですよね．了解です．

2021-12-13 06:43 UTC, sksat commented
あ，conflictしてるんでrebase

2021-12-13 06:46 UTC, sksat commented on git_revision.c
> +#pragma section REPRO
じゃあそうしますかねー

2021-12-13 10:30 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Script/git_revision.bat
> -@ECHO OFF
`src_user/Library/git_revision.h`をどうするかの設定もしくは自動生成ヘッダとして，自動生成しなくて済むなら済むようにしました．それはそれとしてヘッダを自動生成するスクリプトも追加しました．

2021-12-13 10:32 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Script/git_revision.bat
> -@ECHO OFF
バッチファイルのテストはできてないので`./Examples/minimum_user_for_s2e/src/src_user/Script/Git/revision.bat`を実行して`Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h`が自動生成のやつに書き換わるかだけ確認してほしい

2021-12-13 10:38 UTC, sksat commented
これなんで`check_coding_rule`コケてるのかと思ったら`#error`か

2021-12-13 11:22 UTC, meltingrabbit commented
`#error` って別に `""`で囲わなくてもいいので，これは規約チェックスクリプトが良くないっぽいな

2021-12-13 12:19 UTC, sksat commented
まあ`#error`はそうそう使わないですし気持ち的に囲ってた方がよくはあるので気にしなくていいかも

2021-12-13 17:04 UTC, sksat commented
descriptionを修正

2022-01-16 07:38 UTC, sksat commented
conflictしてるのでrebase

2022-01-16 14:15 UTC, sksat commented
超巨大マージがあったので再度rebase

2022-01-16 14:36 UTC, sksat commented
あー，これ`check_encoding.py`が`c2a_core_main.c`を見に行ってないな

2022-01-16 14:37 UTC, meltingrabbit commented
あーたしかに．．．．

2022-01-16 14:42 UTC, sksat commented
これで歴史改変成功したかな

2022-01-16 17:17 UTC, meltingrabbit commented
[Q] `revision.bat/sh` って今，`Script/Git/` 配下にあるけど，これってhookスクリプトにマウントしてるディレクトリなので，買えたほうが良さそう？（このbatの場所をかえるか，hookディレクトリ名をGitHookにするか？）

2022-01-16 17:21 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#define GIT_REVISION_C2A_USER_SHORT 0xfa8a1ec
[IMO] 初期値は0がいい？（スクリプトミスってるのとかわかりやすいので）

2022-01-16 17:23 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#ifndef C2A_USER_GIT_REVISION_H_
[IMO] このファイル，coreの git_revision.hのconfigになってるので，

`user/Settings/git_revision_config.h` とかにしたい？

2022-01-16 17:24 UTC, meltingrabbit commented
[Q] `c2a-core\Examples\minimum_user_for_s2e\src\src_user\Library\git_revision.c` は消し忘れ？

2022-01-16 17:30 UTC, meltingrabbit commented
[Q] `Examples\minimum_user_for_s2e\src\src_user\Script\Git\revision.bat` を実行すると

![image](https://user-images.githubusercontent.com/39541984/149670941-a7cb3029-3f5b-41d3-9fa1-b17f7e03dcfc.png)

と追記になるけど，これは愛してる？

&

と，このgit管理下のファイルを編集することになると，結局 `トラッキングされていると，ビルドする度に無意味なdiffが発生する上誤ってcommitしてしまうことがある．` は解決されない？

2022-01-17 02:15 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#ifndef C2A_USER_GIT_REVISION_H_
たしかにそうかも

2022-01-17 02:16 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#define GIT_REVISION_C2A_USER_SHORT 0xfa8a1ec
いや，これは例であって初期値ではないです(なので`#if 0`)．それはそれとして明らかにおかしい値にしておいてもいいかも．

2022-01-17 02:25 UTC, sksat commented
そうでした．ディレクトリ名変えるかもう1段切るかした方がわかりやすそうですね > `Script/Git/`

これは消し忘れですね > `c2a-core\Examples\minimum_user_for_s2e\src\src_user\Library\git_revision.c`

あー，user部の`git_revision.h`はこのPR後はgitignoreする or user revisionを埋め込まない，としたくて，それはそれとしてexample minimum userの`git_revision.h`は例だけを意図しています．別の場所の方がいいかな......
あと追記になってるのはミスっぽい > 追記

2022-01-17 05:30 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#define GIT_REVISION_C2A_USER_SHORT 0xfa8a1ec
自動生成する場合，ここを `1` にして， `#define C2A_GIT_REVISION_GENERATED` を有効化して，このL14-17をコメントインする（んで，スクリプトで書き換える）んだと思ってたけど，そうではない？

2022-01-18 11:59 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#define GIT_REVISION_C2A_USER_SHORT 0xfa8a1ec
自動生成する場合はこのファイルをgitignoreしてファイルごと生成するつもりでいました(なのでスクリプトがinclude guardも吐いてる)．そもそものモチベーションがこれの自動生成の度にdiffが発生してほしくない，というところにあるので．

2022-01-18 12:02 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#ifndef C2A_USER_GIT_REVISION_H_
と思ったんですが，configになっている場合(CMakeとかでrevisionを全部compile optionで突っ込む or 0を埋め込む)と完全に自動生成される場合があるんですよねこれ．

2022-01-19 06:24 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#ifndef C2A_USER_GIT_REVISION_H_
`C2A_GIT_REVISION_FROM_OPTION` のときとかだよね？

でもまあ，自動生成されたとしても `#define C2A_GIT_REVISION_FROM_OPTION` をここで記してるという意味では，configでいのでは？

2022-01-19 06:26 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#define GIT_REVISION_C2A_USER_SHORT 0xfa8a1ec
> これは例であって初期値ではないです

あ～ `以下のような内容が書き込まれます` ってそういうことか～
`123456...` みたいなあきらかにおかしいわかりやすい例でいいかもね． < 明らかにおかしい値

2022-01-19 06:27 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#define GIT_REVISION_C2A_USER_SHORT 0xfa8a1ec
> 自動生成する場合はこのファイルをgitignoreしてファイルごと生成するつもりでいました

理解．なので https://github.com/ut-issl/c2a-core/pull/82#issuecomment-1013918239 ね．

2022-01-19 06:39 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#define GIT_REVISION_C2A_USER_SHORT 0xfa8a1ec
> 自動生成する場合はこのファイルをgitignoreしてファイルごと生成するつもり

これ，コメント入れておいたほうが良さそう（使い方説明的な意味で）

2022-01-19 10:17 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#define GIT_REVISION_C2A_USER_SHORT 0xfa8a1ec
了解です．たしかにPR bodyにしかろくに説明書いてなかったかも． > コメント

2022-01-19 10:17 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#define GIT_REVISION_C2A_USER_SHORT 0xfa8a1ec
使い方コメント，ソースコードに，だった

2022-01-19 10:20 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Library/git_revision.h
> +#ifndef C2A_USER_GIT_REVISION_H_
たしかに．Cだとヘッダの存在有無で分岐とかできないのでcoreからincludeしてる以上このファイルは存在しなきゃいけないし，やってることはconfigですね．

2022-02-02 10:15 UTC, sksat commented
色々conflictしてたのでrebase

2022-02-02 11:01 UTC, meltingrabbit commented
`///` が刺さっとる．．．

2022-02-02 11:02 UTC, sksat commented
あーなるほどそういうことか...Doxygenの記法であったので使えるかと思ったんですがそっちに弾かれるとは

2022-02-02 11:03 UTC, meltingrabbit commented
`//!<` `/*!<`スタイル採用してる．

2022-02-02 11:03 UTC, sksat commented
了解です

2022-02-02 11:06 UTC, sksat commented
http://www.doxygen.jp/docblocks.html
ちょっと用途違いそうな気もする

2022-02-02 11:07 UTC, sksat commented
```c
/**
 * 
 */
```
はいけるか

2022-02-02 11:08 UTC, meltingrabbit commented
```
/*! @brief 要約説明.
 *         要約説明の続き.
 *
 *  詳細説明がここから始まる.
 */
```

でいいんじゃない？

他で合わせるなら， `@note` で書いちゃうとか

https://github.com/ut-issl/c2a-core/blob/b84c3d051a1e15ab62c8f1a9744957daa4a62a3f/TlmCmd/Ccsds/space_packet.h#L1

2022-02-02 11:08 UTC, sksat commented
よさそう

2022-02-02 11:08 UTC, meltingrabbit commented
今のC2A，ファイル冒頭だけ
```
 /** 
```

で，他は `//!< /*!<` だな

2022-02-02 11:23 UTC, sksat commented
おや？

2022-02-02 11:24 UTC, meltingrabbit commented
あ～，`/*!<` は，知ってるんだけど， `/*!` は認識してないっぽいなぁ．．．

ドキュメントのdoxygen整形，鈴本の方でやっておくので，一旦無視していいよ．（CIとめちゃっててもいいよ）

2022-02-02 11:25 UTC, sksat commented
わかりましたー

2022-02-02 17:28 UTC, meltingrabbit commented on Script/Git/revision.sh
> +#!/bin/bash
git hookとディレクトリかぶってる問題，別PRでやる？

2022-02-02 17:33 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Script/Git/revision.bat
> +REM MEMO: ���̃q�A�h�L�������g��ǂ��̏������wine��cmd.exe(Windows 6.1.7601)���Ɠ����Ȃ��H
こちらの手元のwin10でやった結果．

![image](https://user-images.githubusercontent.com/39541984/152206356-7cac2ac8-5b01-4565-8f6c-609dd8d3ea90.png)


上書きじゃなくて追記されてそう？

deleteがうまく行ってないのかしら？

2022-02-02 17:34 UTC, meltingrabbit commented
`pre-commit` のファイルリストも変更しないとダメそう（git_revision_config.h足さないとダメそう）

2022-02-02 17:34 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Script/Git/revision.bat
> +REM MEMO: ���̃q�A�h�L�������g��ǂ��̏������wine��cmd.exe(Windows 6.1.7601)���Ɠ����Ȃ��H
deleteするの， `git_revision` ではなく `git_revision_config` ？

2022-02-02 17:35 UTC, meltingrabbit commented on Examples/minimum_user_for_s2e/src/src_user/Script/Git/revision.bat
> +REM MEMO: ���̃q�A�h�L�������g��ǂ��̏������wine��cmd.exe(Windows 6.1.7601)���Ɠ����Ȃ��H
いや，書き込むのが，か？

2022-02-02 18:28 UTC, meltingrabbit commented on Script/Git/revision.sh
> +#!/bin/bash
じつはそっちを先にやったほうが良い？ ならこっちでさくっとやっちゃうよ

2022-02-02 18:35 UTC, sksat commented on Script/Git/revision.sh
> +#!/bin/bash
特に依存関係無いので順番はどちらでも〜(が，別PRの方がよさそう)

2022-02-02 18:39 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Script/Git/revision.bat
> +REM MEMO: ���̃q�A�h�L�������g��ǂ��̏������wine��cmd.exe(Windows 6.1.7601)���Ɠ����Ȃ��H
あーrenameし忘れてますね

2022-02-02 18:45 UTC, sksat commented on Examples/minimum_user_for_s2e/src/src_user/Script/Git/revision.bat
> +REM MEMO: ���̃q�A�h�L�������g��ǂ��̏������wine��cmd.exe(Windows 6.1.7601)���Ɠ����Ȃ��H
修正しました

2022-02-03 16:11 UTC, meltingrabbit commented
https://github.com/ut-issl/c2a-core/pull/236 でやってるんで，こっちのレビュー頼みます．

2022-02-04 08:43 UTC, sksat commented on Script/Git/revision.sh
> +#!/bin/bash
#236 がマージされたんでresolve

2023-04-19 16:57 UTC, sksat commented
非常に丁寧な rebase を敢行

2023-04-19 17:03 UTC, sksat commented
`stdint.h` に関する修正のため，再 rebase

2023-04-19 17:19 UTC, sksat commented
少なくとも c2a-core の pre-commit では `git_revision_config.h` をスキップする必要はない（例なので）ため，再度 rebase

2023-04-19 17:23 UTC, sksat commented on Examples/minimum_user/src/src_user/Settings/git_revision_config.h
Shift-JIS 時代から生き残ってた PR だからか表示が壊れてるけど，UTF-8

2023-04-19 17:25 UTC, sksat commented
@meltingrabbit 大 rebase したので，再レビュー頼みます．2nd obc user は同じ変更するだけなので一旦まだやってません & check_coding_rule は文脈的にスクリプトの方が対応できてないっぽい

2023-04-23 22:57 UTC, meltingrabbit commented
> check_coding_rule は文脈的にスクリプトの方が対応できてないっぽい

`/*!` じゃなくて `/*!<` をつかう，ということではなく？

2023-04-23 22:59 UTC, meltingrabbit commented
あ～，doxygen って `/*!` でもいいのか．．．（C2Aの場合， `/*!` は非合法で， `/*!<` のみ合法なのか．．．）

`/*!<` にそろえてもらえると

2023-04-23 23:08 UTC, meltingrabbit commented on Examples/minimum_user/src/src_user/Script/Git/revision.sh
> +EOS
[Q] これって core/Script に置くのはむずかしい？（userのdirectoryがuserごとに違うから無理？）

2023-04-23 23:09 UTC, meltingrabbit commented on c2a_core_main.c
> +const uint32_t GIT_REV_USER_SHORT   = GIT_REVISION_C2A_USER_SHORT;
git_revision.c ではなくこちらに移動させたのってなにか理由ある？

2023-04-23 23:12 UTC, meltingrabbit commented on Examples/minimum_user/src/src_user/Script/Git/revision.bat
> +echo.#define GIT_REVISION_C2A_USER_SHORT 0x$%git_rev_user_short%
```suggestion
echo.#define GIT_REVISION_C2A_USER "%git_rev_user%"
echo.#define GIT_REVISION_C2A_USER_SHORT 0x%git_rev_user_short%
```

2023-04-23 23:18 UTC, meltingrabbit commented on Examples/minimum_user/src/src_user/Script/Git/revision.bat
> +if exist ..\Settings\git_revision_config.h del ..\Settings\git_revision_config.h
```suggestion
if exist ..\..\Settings\git_revision_config.h del ..\..\Settings\git_revision_config.h
```
ところで，追記なのでだるいので，追記ではなく新規にすれば，これ不要？

2023-04-23 23:19 UTC, meltingrabbit commented on Examples/minimum_user/src/src_user/Script/Git/revision.bat
> +) >> Settings\git_revision_config.h
`src_core/Script/Git` に移動してしまうので，
このあとに

```
cd /d %~dp0
```
ほしい

2023-04-23 23:19 UTC, meltingrabbit commented on Examples/minimum_user/src/src_user/Script/Git/revision.bat
> +) >> Settings\git_revision_config.h
.shも

2023-04-24 03:45 UTC, sksat commented
> あ～，doxygen って `/*!` でもいいのか．．．（C2Aの場合， `/*!` は非合法で， `/*!<` のみ合法なのか．．．）
> 
> `/*!<` にそろえてもらえると

https://github.com/ut-issl/c2a-core/pull/82#issuecomment-1027842616 ここからは気持ち変わった？

2023-04-24 03:48 UTC, sksat commented on c2a_core_main.c
> +const uint32_t GIT_REV_USER_SHORT   = GIT_REVISION_C2A_USER_SHORT;
たぶんこれ: https://github.com/ut-issl/c2a-core/pull/82#discussion_r767439607

2023-04-24 03:51 UTC, sksat commented on Examples/minimum_user/src/src_user/Script/Git/revision.sh
> +EOS
user のディレクトリ構造が違うやつはそっちの方が違法だと思う（サポートすべきではない）ので，まあ core に置いてもよいかも．

2023-04-24 03:52 UTC, sksat commented on Examples/minimum_user/src/src_user/Script/Git/revision.sh
> +EOS
ただ，そもそもこのスクリプトを使うのは CMake 不可能なぐらいの渋い環境なので，そんなうまく行くかな，みたいなのもややある

2023-04-24 03:55 UTC, sksat commented on Examples/minimum_user/src/src_user/Script/Git/revision.bat
> +echo.#define GIT_REVISION_C2A_USER_SHORT 0x$%git_rev_user_short%
これはシェルスクリプト書いてからコピって残っちゃったやつか

2023-04-24 03:58 UTC, sksat commented on Examples/minimum_user/src/src_user/Script/Git/revision.bat
> +if exist ..\Settings\git_revision_config.h del ..\Settings\git_revision_config.h
そうかも（しかし bat 自信なし）

2023-05-01 06:19 UTC, meltingrabbit commented on Examples/minimum_user/src/src_user/Script/Git/revision.sh
> +EOS
今後cmakelistsでrevを取得し，shがいらなくなってくので，coreにいらん，という感じなのでこのままでOK

2023-05-01 06:23 UTC, meltingrabbit commented on Examples/minimum_user/src/src_user/Script/Git/revision.bat
> +) >> Settings\git_revision_config.h
shはいらなさそうだった

2023-05-01 06:25 UTC, sksat commented
rebase

2023-05-17 14:54 UTC, sksat commented
rebase

2023-05-17 15:05 UTC, sksat commented on Examples/minimum_user/src/src_user/Script/Git/revision.bat
> +) >> Settings\git_revision_config.h
シェルスクリプトの場合は起動時に別のプロセス切られてるから移動し放題だと思う

2023-05-17 15:08 UTC, sksat commented on Examples/minimum_user/src/src_user/Script/Git/revision.bat
> +if exist ..\Settings\git_revision_config.h del ..\Settings\git_revision_config.h
した

2023-05-17 15:20 UTC, meltingrabbit commented on Examples/minimum_user/src/src_user/Script/Git/revision.bat
> +echo.#define C2A_USER_GIT_REVISION_H_
これが規約違反

2023-05-17 15:20 UTC, meltingrabbit commented on Examples/minimum_user/src/src_user/Script/Git/revision.bat
> +echo.#define C2A_USER_GIT_REVISION_H_
`GIT_REVISION_CONFIG_H_`

2023-05-17 16:07 UTC, meltingrabbit approved these changes
おつ

2023-05-17 16:15 UTC, meltingrabbit requested changes
リリースするのでversion up コミットうってもらって

2023-05-17 16:16 UTC, meltingrabbit approved these changes
おつ２

2023-05-17 16:22 UTC, merged

2023-05-17 16:22 UTC, meltingrabbit commented
2年越しのマージ